Adding --enable-optimize config parameter. Adding extra source files in automake.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -576,7 +576,7 @@ PACKAGE_VERSION='0.1'
 PACKAGE_STRING='flex-bison-cpp-example 0.1'
 PACKAGE_BUGREPORT=''
 
-ac_unique_file="src/test.cc"
+ac_unique_file="src/exprtest.cc"
 ac_subst_vars='SHELL
 PATH_SEPARATOR
 PACKAGE_NAME
@@ -1255,6 +1255,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-optimize       Build with full optimization [default=no]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
 
@@ -2197,6 +2198,24 @@ fi
 if test "$CXXFLAGS" == ""; then
     CXXFLAGS="-g -I/usr/include"
 fi
+
+# enable full optimization by configure switch
+# Check whether --enable-optimize was given.
+if test "${enable_optimize+set}" = set; then
+  enableval=$enable_optimize;  case "${enableval}" in
+          yes)
+                CFLAGS="$CFLAGS -O3 -DNDEBUG";
+                CXXFLAGS="$CXXFLAGS -O3 -DNDEBUG";
+          ;;
+          no) ;;
+          *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-optimize" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-optimize" >&2;}
+   { (exit 1); exit 1; }; } ;;
+          esac
+else
+   optimize=false
+fi
+
 
 # Checks for programs.
 ac_ext=c
@@ -5329,3 +5348,4 @@ if test "$no_create" != yes; then
   # would make configure fail if this is the last instruction.
   $ac_cs_success || { (exit 1); exit 1; }
 fi
+
